language: cpp

os:
  - linux
#  - osx

compiler:
#  - clang
  - gcc

addons:
  apt:
    sources:
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ubuntu-toolchain-r-test; fi; # coveralls

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cd ${TRAVIS_BUILD_DIR}
  - cmake . -Bbin -DCOVERAGE=1
  - cd bin

#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 2.7.6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv global 2.7.6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv rehash; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install cpp-coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv rehash; fi

#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then easy_install pip; fi # pip needed for coveralls
  - pip install --user cpp-coveralls # coveralls

script:
  - make -j4
  - make test
  - ctest -V -j4
  - ./runUnitTests

after_success:
  - coveralls --root . -E ".*thirdParty*" -E ".*CMakeFiles.*" # coveralls