language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
#  - clang

addons:
  apt:
    sources:
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ubuntu-toolchain-r-test; fi; # coveralls

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cd ${TRAVIS_BUILD_DIR}

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user cpp-coveralls; fi


script:
  - cmake .
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$CXX" == "g++" ]]; then
        cmake -DCOVERAGE=1 . ;
      fi
    fi
  - cmake --build .
  - ./runUnitTests

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$CXX" == "g++" ]]; then
        coveralls --root . --exclude thirdParty -E ".*CMakeFiles.*" ;
      fi
    fi
