language: cpp

os:
  - linux
#  - osx

compiler:
  - clang
#  - gcc

addons:
  apt:
    sources:
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ubuntu-toolchain-r-test; fi; # coveralls

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cd ${TRAVIS_BUILD_DIR}

  - cmake -DCOVERAGE=1 . # cmake
  - cmake --build . # cmake build

  # needed for coveralls on osx
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 2.7.6; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv global 2.7.6; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv rehash; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install cpp-coveralls; fi

  # needed for coveralls on linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user cpp-coveralls; fi

script:
  - make -j4
  - ./runUnitTests

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then- coveralls --root . --exclude thirdParty -E ".*CMakeFiles.*"; fi # coveralls