language: cpp

os:
  - linux
#  - osx

compiler:
  - gcc
#  - clang

addons:
  apt:
    sources:
      # coveralls only in linux
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ubuntu-toolchain-r-test; fi;

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cd ${TRAVIS_BUILD_DIR}

  # coveralls only in linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install --user cpp-coveralls;
    fi

  # coveralls only in linux g++
  - if [ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]; then
      echo "ABCABC";
    fi

script:
  - cmake .

  # coveralls only in linux g++
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$CXX" == "g++" ]]; then
        cmake -DCOVERAGE=1 . ;
      fi
    fi

  # this is make
  - cmake --build .

  # needed to get the coverage
  - ./runUnitTests

after_success:
  # coveralls only in linux g++
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$CXX" == "g++" ]]; then
        coveralls --root . --exclude thirdParty -E ".*CMakeFiles.*" ;
      fi
    fi
