language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cd ${TRAVIS_BUILD_DIR}
  - cmake . -Bbin -DCOVERAGE=1
  - cd bin

  #  - brew update
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 2.7.6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv global 2.7.6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv rehash; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install cpp-coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv rehash; fi

  - pip install --user cpp-coveralls # coveralls

script:
  - make -j4
  - ctest -V -j4

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"