language: cpp

os:
- linux
- osx

compiler:
- clang
- gcc

before_install:
- echo $LANG
- echo $LC_ALL
- cd ${TRAVIS_BUILD_DIR}
- cmake . -Bbin
- cd bin

#install:
#  - |
#    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
#      brew install gtest
#    fi
#
#addons:
#  apt:
#    sources:
#    - |
#      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
#        ubuntu-toolchain-r-test
#      fi

script:
- make -j4
- ctest -v