#------------------------------------#
#   ContinousIntegrationPlayground   #
#------------------------------------#

# TODO: how about configuring cmake to install instead of copying the executable?


sudo: false

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

branches:
  # Blacklist the documentation branch
  except:
    - gh-pages

# Environment variables
env:
  global:
    # used in documentation script
    - GH_REPO_NAME: ContinousIntegrationPlayground
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - INPUT_FOR_DOXY: "'$(TRAVIS_BUILD_DIR) $(TRAVIS_BUILD_DIR)/app $(TRAVIS_BUILD_DIR)/lib $(TRAVIS_BUILD_DIR)/tests'"
    - GH_REPO_REF: github.com/MRKonrad/ContinousIntegrationPlayground.git

addons:
  apt:
    sources:
      # coveralls only in linux g++
#      - ubuntu-toolchain-r-test
      - if [ "$CXX" == "g++" ]; then
          ubuntu-toolchain-r-test;
        fi
    packages:
      # for the documentation
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
#      - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
#          doxygen;
#          doxygen-doc;
#          doxygen-latex;
#          doxygen-gui;
#          graphviz;
#        fi

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cd ${TRAVIS_BUILD_DIR}
  - ls ${TRAVIS_BUILD_DIR}

  # coveralls only in linux g++
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
      pip install --user cpp-coveralls;
    fi

script:
  # configure and generate
  - cmake .

  # add coverage option for coveralls (only in linux g++)
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
      cmake -DCOVERAGE=1 . ;
    fi

  # this is make
  - make -j8
  - cmake --build .

  # needed to get the coverage
  - ./tests/ContinousIntegrationPlaygroundTests

after_success:
  # coveralls only in linux g++
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
      coveralls --root . --exclude thirdParty -E ".*CMakeFiles.*" ;
    fi

  - pwd
  - ls ${TRAVIS_BUILD_DIR}
  - ls /home/travis
  - echo ~
  - echo ${INPUT_FOR_DOXY}
  # Generate and deploy documentation only in linux g++
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
      cd $TRAVIS_BUILD_DIR;
      chmod +x generateDocumentationAndDeploy.sh;
      ./generateDocumentationAndDeploy.sh;
    fi

before_deploy:
  - echo "Ready to deploy?"
  - echo ${CXX}
  - cd ${TRAVIS_BUILD_DIR}
  - chmod 777 ContinousIntegrationPlaygroundExe
  - mkdir deployment
  - cp ContinousIntegrationPlaygroundExe deployment/ContinousIntegrationPlaygroundExe_${TRAVIS_BRANCH}_${TRAVIS_OS_NAME}

deploy:
  provider: releases
  api_key:
    secure: hktHPt7mF39LVJhyABALXqMLv0XSrifhYSqi3pV/1shHgsNvMSx63igUKMZBZPnuxsclV8i0PGxKZxScu2Mh28PFJtyfEcD1W+FZURmOS9Fr3FhvlNuiH4SEbVacc0sS8DJEsV8uCeJZj/+cIJMFDmuEiKuSaGNTpFykh8gxJE2tHL7nkijOFUl7PDHWOE7oTGaYd+N0vntk5E26dZ8W8rDDcf8iKhxkGM8wyqDKgrZyp53a6AoadhxrPwUyoM0zuiQWp8pzQAyGMp828dWDxl+NJ/tpz/XtdKMJrLtiD+4ecVHg9gX37r86pTOpfTLDeedfPwIGhjja03G/ED9ZqgySnT3aEdpwae9WQfH6rYmCwg/RKvmnI1y9cFINO8hxwx/GcgusvIibkiKJqPamKkHBTTN9qbHipXXZj+KupPN8Qf0xj8sZRqYEV9eJQaBjKLw8dbi93JtpPRepBmCL8+jGZ7mCDZEJBeUDhXksAMTuecsR2UeKX9+2IydZpj1oEDsgVsL8kC3m1DR2mAZUdxCrjIcwjhosyUNO3GHqKkpnmRkqnF9zPEglPs4RuE8gTGTskpOPd0E/0wQRQAlcCZaCxgrt5a2t7d4qHz4fy7cKeM7nt73eW11I4/ZLgYiXcFk9T7dJuqtHFqOWpi64tV8NYtibbamib9D07zmhiS0=
  file_glob: true
  file:
#    - lib/*
#    - "ContinousIntegrationPlaygroundExe"
    - deployment/*
  skip_cleanup: true
  on:
    tags: true
    condition: ${CXX} == "g++"
#    compiler: gcc # I guess I have to pick one

