# version string format -- This will be overwritten later anyway
version: "{build}"

os:
  - Visual Studio 2017
#  - Visual Studio 2015

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

install:
  - git submodule update --init --recursive

platform:
#  - Win32
  - x64

configuration:
#  - Debug
  - Release

before_build:
  - cmake . -Bbin -A%PLATFORM%

build:
  project: bin\ContinousIntegrationPlayground.sln  # path to Visual Studio solution or project
  parallel: true                                   # enable MSBuild parallel builds
  verbosity: normal                                # MSBuild verbosity level {quiet|minimal|normal|detailed}

after_build:
  - echo %APPVEYOR_BUILD_FOLDER%
  - echo %PLATFORM%
  - echo %APPVEYOR_REPO_BRANCH%
  - echo %APPVEYOR_REPO_TAG_NAME%
  - echo %CONFIGURATION%
  - cd
  - dir %APPVEYOR_BUILD_FOLDER%
  - dir .

test_script:
  - cd bin
  - ctest -V -j2 -C %CONFIGURATION%

before_deploy:
  - echo "Ready to deploy?"


#  - cd ${TRAVIS_BUILD_DIR}
#  - chmod -x ContinousIntegrationPlaygroundExe
#  - mkdir deployment
#  - cp ContinousIntegrationPlaygroundExe deployment/ContinousIntegrationPlaygroundExe_$TRAVIS_BRANCH_$TRAVIS_OS_NAME
deploy:
#  release: ContinousIntegrationPlayground-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: Nmbbo4JCoK5AuN1ugWmE/c8/BAXlpz8Lb7piWDcAAWnT/GFa7fwL20GbXyU9AZSn
  draft: false
  prerelease: false
  artifact: %APPVEYOR_BUILD_FOLDER%\bin\tests\Release\ContinousIntegrationPlayground.exe
  on:
    appveyor_repo_tag: true        # deploy on tag push only
    platform: x64
    configuration: Release