# version string format -- This will be overwritten later anyway
version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmake . -Bbin

build:
  project: Build\ContinousIntegrationPlayground.sln        # path to Visual Studio solution or project
  parallel: true                        # enable MSBuild parallel builds
  verbosity: normal                     # MSBuild verbosity level {quiet|minimal|normal|detailed}